// <auto-generated />
namespace rodriguez.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _explicit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_explicit));
        
        string IMigrationMetadata.Id
        {
            get { return "201705292057571_explicit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
